config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated do
    root to: "categories#index", as: :authenticated_user
  end
  root to: "home#index", as: :unauthenticated_user
  
  resources :entities
  resources :categories
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_and_belongs_to_many :categories
  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: %i[show edit update destroy]

  # GET /entities or /entities.json
  def index
    @entities = Entity.all
  end

  # GET /entities/1 or /entities/1.json
  def show; end

  # GET /entities/new
  def new
    @entity = Entity.new
    @categories = Category.where(author_id: current_user.id) || []
    @category_id = params[:category_id].to_i
  end

  # GET /entities/1/edit
  def edit; end

  # POST /entities or /entities.json
  def create
    category_ids = entity_params[:category_ids].reject(&:empty?).map(&:to_i)
    @entity = Entity.new(entity_params.except(:category_ids, :category_id))

    category_ids.each do |id|
      category = Category.find(id)
      category.entities << @entity
    end

    respond_to do |format|
      if @entity.save
        format.html do
          redirect_to category_url(entity_params[:category_id]), notice: 'Transaction was successfully created.'
        end
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1 or /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to entity_url(@entity), notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1 or /entities/1.json
  def destroy
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to entities_url, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entity
    @entity = Entity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entity_params
    params.require(:entity).permit(:name, :amount, :category_id, category_ids: []).merge(author_id: current_user.id)
  end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_entity.html.erb
<div id="<%= dom_id entity %>">
  <p>
    <strong>Name:</strong>
    <%= entity.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= entity.amount %>
  </p>

</div>

app/views/entities/_form.html.erb
<%= form_with(model: entity) do |form| %>
  <% if entity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
        <% entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="home-input">
    <div class="field">
      <%= form.text_field :name, required:true, placeholder: 'Name' %>
    </div>

    <div class="field">
      <%= form.number_field :amount, step: "0.01", required:true, placeholder: 'Amount' %>
    </div>
  </div>

  <h2 class="select-category">Select Categories</h2>
  <p style="font-size: 12px; text-align: center; margin:0; font-style: italic ">User can select more than one category</p>
  <p style="font-size: 12px; text-align: center; margin:0 0 20px 0; font-style: italic ">Previeous category already selected</p>

  <div class="select-cont">
    <%= form.select :category_ids, @categories.map { |category| [category.name, category.id, selected: @category_id == category.id] }, {include_blank: false}, { multiple: true, required: true} %>
  </div>
  <%= form.hidden_field :category_id, value: @category_id %>

  <div class="create-category-btn">
    <%= form.submit 'Create Transaction' %>
  </div>
<% end %>

app/views/entities/edit.html.erb
<h1>Editing entity</h1>

<%= render "form", entity: @entity %>

<br>

<div>
  <%= link_to "Show this entity", @entity %> |
  <%= link_to "Back to entities", entities_path %>
</div>

app/views/entities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Entities</h1>

<div id="entities">
  <% @entities.each do |entity| %>
    <%= render entity %>
    <p>
      <%= link_to "Show this entity", entity %>
    </p>
  <% end %>
</div>

<%= link_to "New entity", new_entity_path %>

app/views/entities/new.html.erb
<nav class="nav-bar">
  <a href="../" class="back-link"><i class='fa-solid fa-arrow-left fa-xl'></i></a>
  <h2>New Transaction</h2>
  <% if(user_signed_in?) %>
    <%= button_to "Sign out", destroy_user_session_path, :method => :delete, data: {turbo: false}, class: "nav-bar-btn"%>
  <% end %>
</nav>

<%= render "form", entity: @entity %>

app/views/entities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @entity %>

<div>
  <%= link_to "Edit this entity", edit_entity_path(@entity) %> |
  <%= link_to "Back to entities", entities_path %>

  <%= button_to "Destroy this entity", @entity, method: :delete %>
</div>