config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated do
    root to: "categories#index", as: :authenticated_user
  end
  root to: "home#index", as: :unauthenticated_user
  
  resources :entities
  resources :categories
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_and_belongs_to_many :entities
  validates :name, :icon, presence: true

  def self.total_amount(user)
    total_amount = 0
    @categories = Category.where(author_id: user) || []
    @categories.each do |category|
      amount = category.entities.sum(:amount)
      total_amount += amount
    end
    total_amount
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.where(author_id: current_user.id) || []
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
    @entities = @category.entities
    authorize! :read, @category
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon).merge(author_id: current_user.id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="categories-item">
  <div class="category-info">
    <img src="<%= category.icon%>" class='category-icon'>
    <div class="category-name-date">
      <%= link_to category.name , category %>
      <small><%= category.created_at.strftime("%d %b %Y") %></small>
    </div>
  </div>
  <div>
    <p id="amount">$<%= category.entities.sum(:amount)%></p>
    <p><%= button_to "Delete category", category, method: :delete , class: 'category-delete-btn'%></p>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="home-input">
    <div class="field">
      <%= form.text_field :name, placeholder: "Name" %>
    </div>

    <div class="field">
      <%= form.text_field :icon, placeholder: "Icon Link" %>
    </div>
  </div>

  <div class="create-category-btn">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<nav class="nav-bar">
  <a href="../" class="back-link"><i class='fa-solid fa-bars fa-xl'></i></a>
  <h2>Categories</h2>
  <% if(user_signed_in?) %>
    <%= button_to "Sign out", destroy_user_session_path, :method => :delete, data: {turbo: false}, class: "nav-bar-btn"%>
  <% end %>
</nav>
<p class="notice-msg"><%= notice %></p>
<h3 class="total-amount">Total amount: <span>$<%= Category.total_amount(current_user.id)%></span></h3>
<div id="categories" class="categories-container">
  <% @categories.each do |category| %>
    <%= render category %>
  <% end %>
</div>
<div class="height"></div>
<%= link_to "Add a new category", new_category_path, class: 'add-category-btn' %>

app/views/categories/new.html.erb
<p class="notice-msg"><%= notice %></p>
<nav class="nav-bar">
  <a href="../" class="back-link"><i class='fa-solid fa-arrow-left fa-xl'></i></a>
  <h2>New Categoroy</h2>
  <% if(user_signed_in?) %>
    <%= button_to "Sign out", destroy_user_session_path, :method => :delete, data: {turbo: false}, class: "nav-bar-btn"%>
  <% end %>
</nav>

<%= render "form", category: @category %>

app/views/categories/show.html.erb
<nav class="nav-bar">
  <a href="../" class="back-link"><i class='fa-solid fa-arrow-left fa-xl'></i></a>
  <h2>Category</h2>
  <% if(user_signed_in?) %>
    <%= button_to "Sign out", destroy_user_session_path, :method => :delete, data: {turbo: false}, class: "nav-bar-btn"%>
  <% end %>
</nav>
<p class="notice-msg"><%= notice %></p>
<div class="category">
  <div class="category-item-info">
    <img src="<%= @category.icon %>" class='category-icon'>
    <h3><%= @category.name %></h3>
  </div>
    <h4 class="total-amount">Total amount: <span>$<%= @category.entities.sum(:amount)%></span></h4>
  <% if @entities.empty? %>
    <h2 class="transactions-title">Transactions</h2>
    <p class="transactions-title">No transactions have been added yet.</p>
  <% else %>
    <h2 class="transactions-title">Transactions</h2>
      <% @entities.each do |entity| %>
        <div class="transaction">
          <h3><%= entity.name%></h3>
          <h4>$<%= entity.amount%></h4>
        </div>
      <% end %>
  <% end %>
</div>
<div class="height"></div>
<%= link_to "Add a new transaction", "#{new_entity_path}?category_id=#{@category.id}", class: 'add-category-btn', style: 'left: 0' %>س